export const categories = [
    { value: 0, label: "Antique" },
    { value: 1, label: "Arts" },
    { value: 2, label: "Auto parts" },
    { value: 3, label: "Beauty" },
    { value: 4, label: "Bikes" },
    { value: 5, label: "Books" },
    { value: 6, label: "Cameras" },
    { value: 7, label: "Cars" },
    { value: 8, label: "Collectibles" },
    { value: 9, label: "Computers" },
    { value: 10, label: "Computers" },
    { value: 11, label: "Consoles" },
    { value: 12, label: "Education" },
    { value: 13, label: "Electronics" },
    { value: 14, label: "Food" },
    { value: 15, label: "Garden" },
    { value: 16, label: "Headsets" },
    { value: 17, label: "Health" },
    { value: 18, label: "Homemade" },
    { value: 19, label: "Jewelry" },
    { value: 20, label: "Keyboards" },
    { value: 21, label: "Kitchen" },
    { value: 22, label: "Luggage" },
    { value: 23, label: "Men's fashion" },
    { value: 24, label: "Music" },
    { value: 25, label: "Phones" },
    { value: 26, label: "Robotics" },
    { value: 27, label: "Sports" },
    { value: 28, label: "Toys" },
    { value: 29, label: "Video games" },
    { value: 30, label: "Watches" },
    { value: 31, label: "Women's fashion" },
]